language: go

go:
- 1.12.x

git:
  depth: 1

install: skip

jobs:
  include:

    - stage: unit-test
      script:
      - go test -v ./... -coverprofile ./coverage.txt
      - bash <(curl -s https://codecov.io/bash)

    - stage: publish-image
      if: type IN (push)
      script:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - if [ $TRAVIS_EVENT_TYPE = push ]; then export IMAGE=keikoproj/aws-auth:$TRAVIS_BRANCH; fi
      - make docker-build
      - make docker-push
